# Generated by Django 4.2.7 on 2023-11-20 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learn_app', '0004_rename_answer_question_correct_answer_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('speed', models.IntegerField()),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('power', models.IntegerField()),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Thrusters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('thrust', models.IntegerField()),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Weapons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('damage', models.IntegerField()),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('engines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_app.engines')),
                ('shields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_app.shields')),
                ('thrusters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_app.thrusters')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn_app.userprofile')),
                ('weapons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_app.weapons')),
            ],
        ),
    ]
