# Generated by Django 4.2.7 on 2023-11-21 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0002_hangar'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangar',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
