# Generated by Django 4.2.7 on 2023-11-21 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0003_hangar_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hangar',
            old_name='user_profile',
            new_name='profile',
        ),
    ]
