# Generated by Django 4.2.7 on 2023-11-21 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0006_post_comment_hangar_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='hangar',
            name='post',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
