# Generated by Django 4.2.7 on 2023-11-21 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0008_post_comment_hangar_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hangar',
            name='post',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='game_app.post'),
        ),
    ]
