# Generated by Django 4.2.7 on 2023-11-21 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0009_alter_hangar_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hangar',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='hangar',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='game_app.hangar'),
            preserve_default=False,
        ),
    ]
