# Generated by Django 4.2.7 on 2023-11-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0010_remove_hangar_post_post_hangar'),
    ]

    operations = [
        migrations.AddField(
            model_name='engines',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shields',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thrusters',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weapons',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
