# Generated by Django 4.2.7 on 2023-11-18 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn_app', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('choice_one', models.CharField(max_length=300)),
                ('choice_two', models.CharField(max_length=300)),
                ('choice_three', models.CharField(max_length=300)),
                ('choice_four', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=300)),
                ('question_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn_app.questioncard')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn_app.planet')),
            ],
        ),
        migrations.AlterField(
            model_name='questioncard',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn_app.category'),
        ),
    ]
